### ISSUE TITLE
Automatically map `None` to 404

### ISSUE THREAD

**Issue by Tvaroh** [TinkoffCreditSystems/typed-schema#24]
Currently it return `200` with `null` text in the response in case of `None`.

**Comment by Odomontois** [comment]
Could you leave an example

**Comment by Tvaroh** [comment]
@Odomontois my web layer is calling a service like

```scala
trait UserService[F[_]] {
  def findUser(userId: UserId): F[Option[User]]
}
```

I just want to map `None` case to `404` (with corresponding Swagger doc) and `Some(user)` case to `200`.

**Comment by Odomontois** [comment]
Current syntax for that is `$$[ResultType].?`, your handler should return `F[Option[ResultType]]` or `Option[ResultType]` currently finalge - only
