### ISSUE TITLE
[Bug] Empty request path segment matching

### ISSUE THREAD

**Issue by goodmove** [TinkoffCreditSystems/typed-schema#389]
## Problem
1. Path matching behavior depends on the order, in which the endpoints are defined
2. `capture[String]('id)` matches empty string in paths like `/resource/{id}`, but `capture[Int]` does not

## How to reproduce
> Typed Schema version: `v0.12.0`

Consider having two API endpoints:
- `GET /resource/{id}`
- `GET /resource/`

Currently, the api endpoints definition using typed-schema would be:
```scala
  def listBooks =
    prefix('books) :>
      PathEnd :>
      get :>
      key('listBooks) :>
      $$[List[String]]

  def getBook =
    prefix('books) :>
      capture[String]('bookId) :>
      PathEnd :>
      get :>
      key('getBook) :>
      $$[String]
```

and a handler for that could look like this:
```scala
class TestController[F[_]: Sync: RoutedPlus] { self =>
  private val books = Map(
    "1" -> "Book1",
    "2" -> "Book2",
    "3" -> "Book3",
    "4" -> "Book4",
  )

  def routes: H[Response] = MkService[H](api)(self)
  def listBooks(): List[String] = books.values.toList
  def getBook(bookId: String): String = books.getOrElse(bookId, "Not found")

}
```

where `PathEnd` checks that all symbols in the request path have been consumed.

#### 1.1
Final definition:
```scala
  def api = getBook <|> listBooks
```
Actual:
```bash
> curl http://localhost:8080/books
< "Not found"
```
Expected:
```bash
> curl http://localhost:8080/books
< ["Book1","Book2","Book3","Book4"]
```
#### 1.2
Final definition:
```scala
  def api = listBooks  <|> getBook
```
Actual matches expected
```bash
> curl http://localhost:8080/books
< ["Book1","Book2","Book3","Book4"]
```

### Case 2: Matching inconsistency
Final definition:
```scala
  def api = getBook <|> listBooks
```
Let's modify `getBook` to accept `Int`:
```scala
  def getBook =
    prefix('books) :>
      capture[Int]('bookId) :>
      PathEnd :>
      get :>
      key('getBook) :>
      $$[String]
```

And call the API again (actual matches expected):
```bash
> curl http://localhost:8080/books
< ["Book1","Book2","Book3","Book4"]
```

**Comment by REDNBLACK** [comment]
Fixed in https://github.com/TinkoffCreditSystems/typed-schema/pull/442
