### ISSUE TITLE
Consider updating Shapeless to milestone version

### ISSUE THREAD

**Issue by REDNBLACK** [TinkoffCreditSystems/typed-schema#446]
I'm getting notable improvement of compilation speed in latest milestone 2.4.0-M1, also they've fixed nasty duplication bug in RemoveAll. 
@Odomontois WDYT, should we consider merging milestones, if they contain quality of life improvements and bugfixes?

**Comment by danslapman** [comment]
@REDNBLACK is 2.4.0-M1 not backwards compatible? I mean would anything break if you force shapeless version to 2.4.0-M1 in your project (and use current typed-schema)? Currently we already have too many pain points and I this it's quite undesirable to introduce one more.

**Comment by REDNBLACK** [comment]
Odo has shown me in private conversation other possible compilation errors, closing this.
