### ISSUE TITLE
Move derevo integration into this repo

### ISSUE THREAD

**Issue by danslapman** [TinkoffCreditSystems/typed-schema#448]
Today we have a cross-reference between typed-schema artifacts and derevo-core, which introduces some of inconvenience when an binary incompatible version of typed-schema comes out. I think we should migrate derevo-tschema into this repository (and release them simultaneously). What do you think, @Odomontois ?

**Comment by Odomontois** [comment]
derevo-tschema is actually a deprecated module, I suppose we should just remove this
All derivations for derevo are available as corresponding type companions

(Swagger, HttpParam, AsOpenApiParam) + additional from the finagle custom module
(plainError, jsonError) and AsResponse.{...} for sealed traits

**Comment by danslapman** [comment]
@REDNBLACK what You mean by "invalid"?

**Comment by REDNBLACK** [comment]
@danslapman as per title, derevo integrations are already in this repo
