### ISSUE TITLE
Cooperation between you and Typedapi

### ISSUE THREAD

**Issue by pheymann** [TinkoffCreditSystems/typed-schema#5]
Hi,
I am gonna (miss)use your issue tracker to start this conversation as I am not able to find any mail address or Gitter channel. So, mea culpa :).

Do you know [Typedapi](https://github.com/pheymann/typedapi)? It is basically the same idea, bringing Servant to Scala. But so far (at least in its release branch [0.1.0-release](https://github.com/pheymann/typedapi/tree/0.1.0-release)) it supports the server and client side and the following frameworks/libs: akka-http, http4s and Scalaj-Http. Furthermore, it compiles to JavaScript with ScalaJS.

It seems to me that your project is at the beginning (?). Maybe a cooperation between the two projects makes sense to not develop the same thing twice. And especially running in the same problems twice :D.

Let me know what you think.

**Comment by Odomontois** [comment]
Hi.
Yeah, I definitely hear about your awesome project and would gladly cooperate.

My project is about 1.5 year old. It was an internal Tinkoff bank project. I had intent to publish it from the very start, but it is not so easy in bank business.
I have published it without the history to hide sensitive informarion, so it misses previous 225 commits 😀

**Comment by pheymann** [comment]
Hi @Odomontois ,
I realized you support swagger generation. There are also plans to add it to my lib but I haven't found a (satisfying) solution for the following problem:

> How to add comments?

I mean, it is "simple" enough to generate the basic documentation from the type/value information available, but what I found crucial is to have comments. Otherwise, it is hard for people to realy understand what is happening.

Did you find a way to incorporate comments into your (did see it so far but maybe I missed it) without cluttering the api declaration? I still haven't found a satifying way.

**Comment by Odomontois** [comment]
Hi. Sorry for the late answer. Haven't been fully integrated OSS with my life
I have couple of distinct solutions here.
First are implicits with default arguments like here

https://github.com/TinkoffCreditSystems/typed-schema/blob/master/src/main/scala/ru/tinkoff/tschema/swagger/SwaggerTypeable.scala#L212

and here

https://github.com/TinkoffCreditSystems/typed-schema/blob/master/src/main/scala/ru/tinkoff/tschema/swagger/SwaggerTypeable.scala#L269

Second one, more like runtime one - injecting definitions from .properties bundles created like that https://github.com/TinkoffCreditSystems/typed-schema/blob/master/src/main/scala/ru/tinkoff/tschema/swagger/PathDescription.scala

Here the example of injecting https://github.com/TinkoffCreditSystems/typed-schema/blob/master/examples/src/main/scala/ru/tinkoff/tschema/examples/TestServer.scala#L22

And here is examples of .property file 
https://github.com/TinkoffCreditSystems/typed-schema/tree/master/examples/src/main/resources
